name = "Hyde Forked"
license = "MIT"
licenselink = "https://github.com/nmarley/hugo-theme-hyde-forked/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes"]
min_version = 0.53

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
